import {
  Menu,
  X,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ArrowRight,
  ArrowUpRight,
  Check,
  CheckCircle,
  AlertTriangle,
  AlertCircle,
  Info,
  Sun,
  Moon,
  Mail,
  Phone,
  MapPin,
  Linkedin,
  Instagram,
  SearchX,
  Inbox,
  FileQuestion,
  Building,
  Server,
  Cloud,
  Sparkles,
  Headset,
  Compass,
  Twitter,
  MessageCircle,
  Link2,
  Clock,
  Ticket,
  QrCode,
  Wallet,
  Gift,
  LayoutTemplate,
  Calendar,
  Users,
  Mic,
  Quote,
  type LucideIcon,
} from 'lucide-react';

/** Icon names as used throughout the design system (matches Lucide's own kebab-case names). */
export const ICONS = {
  menu: Menu,
  x: X,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  check: Check,
  'check-circle': CheckCircle,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  info: Info,
  sun: Sun,
  moon: Moon,
  mail: Mail,
  phone: Phone,
  'map-pin': MapPin,
  linkedin: Linkedin,
  instagram: Instagram,
  'search-x': SearchX,
  inbox: Inbox,
  'file-question': FileQuestion,
  building: Building,
  server: Server,
  cloud: Cloud,
  sparkles: Sparkles,
  headset: Headset,
  compass: Compass,
  twitter: Twitter,
  'message-circle': MessageCircle,
  link: Link2,
  clock: Clock,
  ticket: Ticket,
  'qr-code': QrCode,
  wallet: Wallet,
  gift: Gift,
  'layout-template': LayoutTemplate,
  calendar: Calendar,
  users: Users,
  mic: Mic,
  quote: Quote,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
